# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tj/Documents/Xilinx/Projects/unity_exercise/unity_exercise.srcs/sources_1/bd/unity_excercise_design_1/ip/unity_excercise_design_1_processing_system7_0_0/unity_excercise_design_1_processing_system7_0_0.xci
# IP: The module: 'unity_excercise_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tj/Documents/Xilinx/Projects/unity_exercise/unity_exercise.srcs/sources_1/bd/unity_excercise_design_1/ip/unity_excercise_design_1_processing_system7_0_0/unity_excercise_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'unity_excercise_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/tj/Documents/Xilinx/Projects/unity_exercise/unity_exercise.srcs/sources_1/bd/unity_excercise_design_1/ip/unity_excercise_design_1_processing_system7_0_0/unity_excercise_design_1_processing_system7_0_0.xci
# IP: The module: 'unity_excercise_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tj/Documents/Xilinx/Projects/unity_exercise/unity_exercise.srcs/sources_1/bd/unity_excercise_design_1/ip/unity_excercise_design_1_processing_system7_0_0/unity_excercise_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'unity_excercise_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
