webtalk_init -webtalk_dir /home/tj/Documents/Xilinx/Projects/WaveGenerator/WaveGenerator.sim/sim_1/behav/xsim/xsim.dir/TB_waveGen_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 21 15:30:51 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "10c827c6-bb82-450e-8a08-2b4e78f4ec30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "24c54dfe6b3a4c0592b57e66418f363b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3311.718 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.98_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128212_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1824696081 -regid "" -xml /home/tj/Documents/Xilinx/Projects/WaveGenerator/WaveGenerator.sim/sim_1/behav/xsim/xsim.dir/TB_waveGen_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tj/Documents/Xilinx/Projects/WaveGenerator/WaveGenerator.sim/sim_1/behav/xsim/xsim.dir/TB_waveGen_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tj/Documents/Xilinx/Projects/WaveGenerator/WaveGenerator.sim/sim_1/behav/xsim/xsim.dir/TB_waveGen_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
