# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/new_cnstr.xdc

# Block Designs: bd/unity_excercise_design_1/unity_excercise_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1 || ORIG_REF_NAME==unity_excercise_design_1} -quiet] -quiet

# IP: bd/unity_excercise_design_1/ip/unity_excercise_design_1_processing_system7_0_0/unity_excercise_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1_processing_system7_0_0 || ORIG_REF_NAME==unity_excercise_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/unity_excercise_design_1/ip/unity_excercise_design_1_pl_top_0_0/unity_excercise_design_1_pl_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1_pl_top_0_0 || ORIG_REF_NAME==unity_excercise_design_1_pl_top_0_0} -quiet] -quiet

# IP: bd/unity_excercise_design_1/ip/unity_excercise_design_1_axi_uartlite_0_1/unity_excercise_design_1_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1_axi_uartlite_0_1 || ORIG_REF_NAME==unity_excercise_design_1_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/unity_excercise_design_1/ip/unity_excercise_design_1_ps7_0_axi_periph_1/unity_excercise_design_1_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==unity_excercise_design_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/unity_excercise_design_1/ip/unity_excercise_design_1_rst_ps7_0_50M_1/unity_excercise_design_1_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1_rst_ps7_0_50M_1 || ORIG_REF_NAME==unity_excercise_design_1_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/unity_excercise_design_1/ip/unity_excercise_design_1_auto_pc_0/unity_excercise_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_excercise_design_1_auto_pc_0 || ORIG_REF_NAME==unity_excercise_design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/unity_excercise_design_1/unity_excercise_design_1_ooc.xdc
